### ISSUE TITLE
[feature request] alternative buy/sell key

### ISSUE THREAD

**Issue by craziedde** [DominikBritz/NinjaTrader-indicators-strategies#5]
Buy → `left ctrl + left mouse`
Sell → `left ctrl + right mouse`

This second hotkey option would be nice

Thank you for all super useful indicators!

Ed

**Comment by DominikBritz** [comment]
I prefer having two separate keys instead.

**Comment by craziedde** [comment]
> I prefer having two separate keys instead.

We don't have to change default hotkeys.
Can we just add alternative?

**Comment by DominikBritz** [comment]
I tried, but I can't find a way to check for a right mouse button click. Apparently, NinjaTrader's own right-click menu blocks that.

**Comment by DominikBritz** [comment]
I've committed the current work in progress in this branch. Maybe in the future I can fix this. https://github.com/DominikBritz/NinjaTrader-indicators-strategies/tree/TradingFromChart2

**Comment by craziedde** [comment]
Yes, I can see the issue with right click.
Thank you for considering this request for future implementation..

**Comment by Mindset7of9** [comment]
Hi Dominic
Mindset here.
Great work and thanks for the credit. Just some thoughts on improvement that I did.
Consider using GetCurrentBid() and GetCurrentAsk() instead of Close[0] as sometimes the spread can be wide and or high volatility can make the indicator fall over - also maybe a Try- Catch so that it doesn't stop altogether?
